### ISSUE TITLE
3G / 4G Sim 2

### ISSUE THREAD

**Issue by Pr0gmaT1k** [Deepflex/android_device_elephone_p6000_pro_cm12_1#2]
I cant get 3G / 4G on Sim 2, only Edge / GPRS (preferred network = 4G).
The issue appears event if the slot 1 is empty.
The same sim work perfectly on slot 1.

**Comment by Deepflex** [comment]
Hi. 
It is normally. Sim 2 only E

**Comment by Pr0gmaT1k** [comment]
On stock elephone rom i got 4G when preferred sim data is sim 2

**Comment by Deepflex** [comment]
Yes. Here CM ril. Not modem trouble.

**Comment by Pr0gmaT1k** [comment]
You probably right. I close the issue, thanks.
